name: CI Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    needs: ["check_secrets"]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make dev-venv SYSTEM_PYTHON=python
      - name: Lint
        run: |
          make dev-lint
      - name: Test with pytest
        run: |
          make dev-pytest
